name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:11-3.3
        env:
          POSTGRES_DB: lametro
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libxml2-dev
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools-scm<7.0"
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        echo "TOKEN='faketoken'" > lametro/secrets.py 
        pytest -sv
